{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "interview-app.fullname" . }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "interview-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.metrics.interval }}
{{- end }}
