---
name: Validate Helm Chart

on:
  push:
    branches:
      - master
    paths:
      - 'sre/interview-app/**'
      - '.github/workflows/validate-helm.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'sre/interview-app/**'
      - '.github/workflows/validate-helm.yml'
      - '.github/workflows/validate-helm-reusable.yml'

jobs:
  validate:
    permissions:
      contents: read
    uses: ./.github/workflows/validate-helm-reusable.yml
